# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire’
#pod 'CKWaveCollectionViewTransition'
pod 'ASCollectionView'
pod 'ExpandingMenu'
pod 'DKImagePickerController'
pod 'FlexiCollectionViewLayout'
#pod 'RealmSwift','2.1.2'
#
#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '3.0'
#        end
#    end
#end
  # Pods for MyApp

  #target 'MyAppTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  #target 'MyAppUITests' do
    #inherit! :search_paths
    # Pods for testing
  #end

end
